server:
  port: 8090

# Where to go to check the incoming token
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8091/auth/realms/test-realm/protocol/openid-connect/certs            
